In [1]:
import numpy as np

In [2]:
# Creating Arrays from Python Lists
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [13]:
# Nested lists results in multi-dimensional arrays
np.array([range(i,i+3) for i in [2,4,6] ])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [4]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
# Create a 3x5 floating-point array filled with ones
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
# Create an array filled with a linear sequence
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
# Create a 3x3 array of random integers
np.random.randint(0,10,(3,3))

array([[5, 9, 2],
       [1, 5, 4],
       [7, 1, 0]], dtype=int32)

In [9]:
# Create a 3x3 array of normally distributed random values with mean 0 and std 1
np.random.normal(0,1,(3,3))

array([[-1.04831159, -0.2724256 ,  1.20958687],
       [ 0.32829754,  3.00849941,  1.17674274],
       [ 0.69029922,  0.05377215,  0.78992658]])

In [11]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])